version: '3'
name: trainee-software_projeto-3
services: 
  influxdb:
    image: bitnami/influxdb:latest
    container_name: db
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_ADMIN_USER_PASSWORD=password123
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=password
      - INFLUXDB_DB=my_database
      - INFLUXDB_ADMIN_USER_TOKEN=token
    ports:
      - 8086:8086
    volumes:
      - 'db_data:/bitnami/influxdb'
  grafana:
    image: bitnami/grafana:8
    container_name: client
    ports:
      - '3000:3000'
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "bitnami"

volumes:
  db_data:
    driver: local
